### ISSUE TITLE
Error: InvalidImageName

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/helm-chart#19]
Trying to re-deploy the cluster with the new chart and docker image, I am getting this error

```
Failed to apply default image tag "None:None": couldn't parse image reference "None:None": invalid reference format: repository name must be lowercase
```

**Comment by rabernat** [comment]
A similar error was discussed in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/472

**Comment by rabernat** [comment]
My first guess is that the new docker image tag is somehow invalid. Here are the relevant lines

https://github.com/pangeo-data/helm-chart/blob/master/pangeo/values.yaml#L20-L23
```
  singleuser:
    image:
      name: pangeo/notebook
      tag: 2018-04-27
```

The tag appears to exist in docker:
https://hub.docker.com/r/pangeo/notebook/tags/

**Comment by rabernat** [comment]
FYI, I deployed this as follows

```bash
helm upgrade jupyter pangeo/pangeo -f jupyter-config.yaml -f secret-config.yaml --version 0.1.0-36c7a95
```

Here are the full contents of my [jupyter-config.yaml](https://github.com/pangeo-data/pangeo/blob/2a676ea57ee77fe0bf317a218b06d7ceb0185033/gce/jupyter-config.yaml)
```yaml
jupyterhub:
  singleuser:
    cmd: ['start-singleuser.sh']
    extraEnv:
      EXTRA_PIP_PACKAGES: >-
      GCSFUSE_BUCKET: pangeo-data
    storage:
      extraVolumes:
        - name: fuse
          hostPath:
            path: /dev/fuse
      extraVolumeMounts:
        - name: fuse
          mountPath: /dev/fuse
    cloudMetadata:
      enabled: true
    cpu:
      limit: 4
      guarantee: 1
    memory:
      limit: 14G
      guarantee: 4G

  hub:
    extraConfig: |
      from kubernetes import client
      def modify_pod_hook(spawner, pod):
          pod.spec.containers[0].security_context = client.V1SecurityContext(
              privileged=True,
              capabilities=client.V1Capabilities(
                  add=['SYS_ADMIN']
              )
          )
          return pod
      c.KubeSpawner.modify_pod_hook = modify_pod_hook
      c.JupyterHub.logo_file = '/usr/local/share/jupyter/hub/static/custom/images/logo.png'
      c.JupyterHub.template_paths = ['/usr/local/share/jupyter/hub/custom_templates/',
                                    '/usr/local/share/jupyter/hub/templates/']
    image:
      name: jupyterhub/k8s-hub
      tag: v0.6
    extraVolumes:
      - name: custom-templates
        gitRepo:
          repository: "https://github.com/pangeo-data/pangeo-custom-jupyterhub-templates.git"
          revision: "b09721bb1a1248dc115730d3c8a791600eae257e"
    extraVolumeMounts:
      - mountPath: /usr/local/share/jupyter/hub/custom_templates
        name: custom-templates
        subPath: "pangeo-custom-jupyterhub-templates/templates"
      - mountPath: /usr/local/share/jupyter/hub/static/custom
        name: custom-templates
        subPath: "pangeo-custom-jupyterhub-templates/assets"

  cull:
    enabled: true
    users: false
    timeout: 1200
    every: 600
```

**Comment by rabernat** [comment]
@jacobtomlinson -- if you're still online, I would love to pick your brain for a second...

**Comment by jacobtomlinson** [comment]
I'm around! I'll DM you on Gitter. We should have a Gitter or Slack or something for Pangeo.

**Comment by mrocklin** [comment]
If we do use a chat room then I have a preference for gitter over slack if
possible.  It's nice to have only one window for chatting rather than one
for every project.

**Comment by jacobtomlinson** [comment]
Agreed!

**Comment by rabernat** [comment]
Also of note, I get this warning:
```
2018/04/30 10:32:07 warning: cannot overwrite table with non table for extraConfig (map[])
2018/04/30 10:32:07 warning: cannot overwrite table with non table for extraConfig (map[])
```

Also noted in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/653

**Comment by jacobtomlinson** [comment]
I successfully created a new pangeo from the new version:

```
helm install pangeo/pangeo --name pangeo-test --namespace pangeo-test --version v0.1.0-36c7a95 -f values.yaml
```

```
# values.yaml

jupyterhub:
  hub:
    cookieSecret: "somereallylongthing"
  proxy:
    secretToken: "somereallylongthing"
rbac:
  enabled: true
```

This suggests the issue is either to do with upgrading the release or an incompatibility with the config in [jupyter-config.yaml](https://github.com/pangeo-data/pangeo/blob/2a676ea57ee77fe0bf317a218b06d7ceb0185033/gce/jupyter-config.yaml).
