### ISSUE TITLE
Helm charts point to Docker images not available on Dockerhub

### ISSUE THREAD

**Issue by jgerardsimcock** [pangeo-data/helm-chart#46]
xref here: https://github.com/pangeo-data/pangeo/issues/337

The two most recent [helm-charts](https://pangeo-data.github.io/helm-chart/) are tagged with commits that don't correspond to the image tags on [dockerhub](https://hub.docker.com/r/pangeo/notebook/tags/). 

If I recall, chartpress is not pushing images to dockerhub, right? So this is still a manual, two-step process?

**Comment by jacobtomlinson** [comment]
Interesting. We should update this to push the docker images as a manual step is not sustainable.

**Comment by rabernat** [comment]
Yes we should. That’s what #40 should accomplish. 

We just need someone with sufficient tragic experience to help get our chartpress configs sorted out. I don’t have the expertise or time to do it myself.

**Comment by jgerardsimcock** [comment]
Ok. I am happy to help with this. I might need some assistance as I am not sure if the whole chartpress thing applies to the notebook/worker link that pangeo is trying to preserve. We've been unable to deploy both the worker and notebook using Chartpress. Its not clear to me how to add the worker  'valuesPath': value in the chartpress.yaml file. This may be a question for @yuvipanda. 

My next attempt was to have travis deploy helm charts after the docker images build by checking out the helm-chart repo, updating and pushing to gh-pages branch. I've been unsuccessful at this so far. But this should in theory work. Do either of you see anything glaringly inaccurate? 

```
sudo: required
services:
  - docker

env:
  global:
    - TAG=2018-07-18.01
  matrix:
    - IMAGE_NAME=notebook
    - IMAGE_NAME=worker
    - IMAGE_NAME=worker-tc

install:
  - cd $IMAGE_NAME
  - docker build --pull --cache-from rhodium/$IMAGE_NAME -t rhodium/$IMAGE_NAME:$TAG .

script:
  - docker images rhodium/$IMAGE_NAME:$TAG

deploy:
  provider: script
  script: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" && docker push "rhodium/$IMAGE_NAME:$TAG"
  skip_cleanup: true
  on:
    branch: master
after_deploy:
  script:
    - curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash
    # set-up deploy key
    - openssl aes-256-cbc -K $encrypted_19fb998dc11c_key -iv $encrypted_19fb998dc11c_iv -in github_deploy_key.enc -out github_deploy_key -d
    - chmod 600 github_deploy_key
    #clone our helm repo
    - git clone git@github.com:RhodiumGroup/helm-chart.git
    #update the tag for the helm chart
    - cd helm-chart
    - python update_helm_tag.py -$TAG
    #create the helm chart with the new tag
    - helm package rhg-hub/
    #add information to gh-pages repo
    - git checkout gh-pages
    - git add rhg-hub*.tgz
    - helm repo index .
    - git commit -am 'add new helm chart tag=$TAG'
    #push to gh-pages
    - git push 
  on:
    branch: master
```

@jacobtomlinson or @rabernat If I can get some help on the actual deploy, I can take it from there.
